<a href="https://colab.research.google.com/github/JAbrams204/AirBnB_Clone/blob/main/3_1_Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Welcome to Machine Learning using Python!')

Welcome to Machine Learning using Python!


NumPy - Numerical Python

Advantages of NumPy Arrays
1.   Allows several Mathematical Operations
2.   Faster operations

In [ ]:
import numpy as np

The analysis of the time taken for a computation between a Python List and NumPy

In [ ]:
from time import process_time

Computation time taken by a List

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i + 5 for i in python_list]

end_time = process_time()

#print(python_list)

print(end_time - start_time)

0.0015412070000007105


Computation time taken by NumPy

In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)



0.00014993299999943588


NumPy Arrays

In [ ]:
#List
list01 = [1, 2, 3, 4, 5]
print(list01)
type(list01)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# Create a One Dimensional Array

one_array = np.array([10, 20, 30, 40, 50])
print(one_array)
print()
one_array.shape

[10 20 30 40 50]



(5,)

In [ ]:
# Create a Two Dimensional Array

two_array = np.array([(3, 5, 7, 9), (2, 4, 6, 8)])
print(two_array)
print()
two_array.shape

[[3 5 7 9]
 [2 4 6 8]]



(2, 4)

In [ ]:
fl_array = np.array([(1, 2, 3), (4, 5, 6)], dtype=float)
print(fl_array)

[[1. 2. 3.]
 [4. 5. 6.]]


Initial Placeholders in NumPy Arrays

In [ ]:
# Create NumPy Array of Zeros

ze_array = np.zeros((3,4))
print(ze_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Create NumPy Array of Ones
on_array = np.ones((3,3))
print(on_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Create a NumPy Array of particular Value

fu_array = np.full((4,4),5)
print(fu_array)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# Create an Identity Matrix

id_array = np.eye(5)
print(id_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Create a NumPy Array of Random Value

rn_array = np.random.random((3,3))
print(rn_array)

[[0.27275546 0.96142353 0.83468385]
 [0.71600291 0.83159532 0.14633281]
 [0.81402038 0.69383044 0.6134296 ]]


In [ ]:
# Create a NumPy Array of Random Integer Value within a specified range

rnr_array = np.random.randint(10, 50, (3,3))
print(rnr_array)

[[16 27 29]
 [22 33 41]
 [25 33 22]]


In [ ]:
# Create an Array of evenly spaced Values --> specifying the number of values required

l_array = np.linspace(10, 30, 6)
print(l_array)



[10. 14. 18. 22. 26. 30.]


In [ ]:
# Create an Array of evenly spaced Values --> specifying the step!

s_array = np.arange(10,30,6)
print(s_array)

[10 16 22 28]


In [ ]:
# Convert a List to an Array

list02 = [10, 20, 30, 40, 50]

conv_array = np.asarray(list02)
print(conv_array)
print()
type(conv_array)

[10 20 30 40 50]



numpy.ndarray

Analysing NumPy Arrays

In [ ]:
my_array = np.random.randint(10,50, (4,4))
print(my_array)

[[18 35 21 24]
 [49 49 16 23]
 [23 46 12 26]
 [18 25 21 35]]


In [ ]:
# Array Dimension

print(my_array.ndim)

2


In [ ]:
# Number of Element in an Array

print(my_array.size)

16


In [ ]:
# Checking the Datatype of the Values in the Array

print(my_array.dtype)

int64


In [ ]:
# Mathematical Operation on a NumPy Array

In [ ]:
list_a = [1,2,3,4,5]
list_b = [6, 7, 8, 9, 10]

print(list_a + list_b)      # the addition of these lists results in a concatenation instead of addition!

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
array_a = np.random.randint(0,10, (3,3))
array_b = np.random.randint(10,20, (3,3))

print(array_a)
print()
print(array_b)



[[1 0 4]
 [2 1 7]
 [1 8 6]]

[[18 16 10]
 [10 12 12]
 [18 14 13]]


In [ ]:
print(array_a + array_b)
print()
print(array_a - array_b)
print()
print(array_a * array_b)
print()
print(array_a / array_b)


[[19 16 14]
 [12 13 19]
 [19 22 19]]

[[-17 -16  -6]
 [ -8 -11  -5]
 [-17  -6  -7]]

[[ 18   0  40]
 [ 20  12  84]
 [ 18 112  78]]

[[0.05555556 0.         0.4       ]
 [0.2        0.08333333 0.58333333]
 [0.05555556 0.57142857 0.46153846]]


In [ ]:
# Alternatively, we could perform the same computation using functions

array_c = np.random.randint(0,10, (3,3))
array_d = np.random.randint(10,20, (3,3))

print(array_c)
print()
print(array_d)

[[8 9 4]
 [6 8 6]
 [6 7 9]]

[[14 13 16]
 [15 10 11]
 [16 10 17]]


In [ ]:
print(np.add(array_c, array_d))
print()
print(np.subtract(array_c, array_d))
print()
print(np.multiply(array_c, array_d))
print()
print(np.divide(array_c, array_d))

[[22 22 20]
 [21 18 17]
 [22 17 26]]

[[ -6  -4 -12]
 [ -9  -2  -5]
 [-10  -3  -8]]

[[112 117  64]
 [ 90  80  66]
 [ 96  70 153]]

[[0.57142857 0.69230769 0.25      ]
 [0.4        0.8        0.54545455]
 [0.375      0.7        0.52941176]]


Array Manipulations

In [ ]:
new_array = np.random.randint(0, 10, (2, 3))
print(new_array)
print()
print(new_array.shape)

[[7 3 9]
 [4 7 8]]

(2, 3)


In [ ]:
# Transpose of an Array

trans = np.transpose(new_array)
print(trans)
print()
print(trans.shape)

[[7 4]
 [3 7]
 [9 8]]

(3, 2)


In [ ]:
# An alternative approach to Array transpose

new_array02 = np.random.randint(0, 10, (2, 3))
print(new_array02)
print()
print(new_array02.shape)



[[3 5 4]
 [7 5 8]]

(2, 3)


In [ ]:
trans02 = new_array02.T
print(trans02)
print()
print(trans02.shape)

[[3 7]
 [5 5]
 [4 8]]

(3, 2)


In [ ]:
# Reshaping an Array

new_array03 = np.random.randint(0, 10, (2,3))
print(new_array03)
print()
print(new_array03.shape)

[[8 4 3]
 [3 3 6]]

(2, 3)


In [ ]:
new_array04 = new_array03.reshape(3,2)
print(new_array04)
print()
print(new_array04.shape)

[[8 4]
 [3 3]
 [3 6]]

(3, 2)
